import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { Directory, File, Paths } from "expo-file-system";
import * as ImagePicker from "expo-image-picker";
import { useState } from "react";
import { Alert, Image, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";

import { colors } from "@/components/remo-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useLibrary } from "@/lib/library-context";
import { usePlayer } from "@/lib/player-context";

export default function EditAudioScreen() {
  const router = useRouter();
  const { currentItem, setCurrentItem } = usePlayer();
  const { updateMediaItem } = useLibrary();
  const [title, setTitle] = useState(currentItem?.title ?? "");
  const [artist, setArtist] = useState(currentItem?.artist ?? "");
  const [album, setAlbum] = useState(currentItem?.album ?? "");
  const [lyrics, setLyrics] = useState(currentItem?.lyrics ?? "");
  const [coverUri, setCoverUri] = useState(currentItem?.thumbnailUri ?? "");
  if (!currentItem || currentItem.mediaType !== "audio") return <ScreenContainer><View style={styles.empty}><Text style={styles.emptyText}>اختر أغنية أولاً.</Text></View></ScreenContainer>;
  const chooseCover = async () => { const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ["images"], allowsEditing: true, aspect: [1, 1], quality: 0.85 }); if (!result.canceled) setCoverUri(saveCoverLocally(result.assets[0].uri)); };
  const save = async () => { const changes = { title: title.trim() || currentItem.title, artist: artist.trim() || "فنان غير معروف", album: album.trim() || "بدون ألبوم", lyrics: lyrics.trim(), thumbnailUri: coverUri || undefined }; await updateMediaItem(currentItem.id, changes); setCurrentItem({ ...currentItem, ...changes }); Alert.alert("تم حفظ التعديلات", "حُفظت بيانات المسار وتخصيصاته محلياً على جهازك."); router.back(); };
  return <ScreenContainer edges={["top", "bottom", "left", "right"]}><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.headerButton}><MaterialIcons name="arrow-forward" size={24} color={colors.text} /></Pressable><Text style={styles.headerTitle}>تحرير الأغنية</Text><Pressable onPress={() => void save()} style={styles.saveHeader}><Text style={styles.saveHeaderText}>حفظ</Text></Pressable></View><Pressable onPress={() => void chooseCover()} style={styles.coverPicker}>{coverUri ? <Image source={{ uri: coverUri }} style={styles.coverImage} /> : <View style={styles.coverFallback}><MaterialIcons name="music-note" size={43} color={colors.cyan} /></View>}<View style={styles.coverEdit}><MaterialIcons name="photo-camera" size={17} color={colors.background} /></View></Pressable><Text style={styles.coverHint}>اضغط لاختيار غلاف أو خلفية مخصصة</Text><Field label="اسم الأغنية" value={title} onChangeText={setTitle} /><Field label="الفنان" value={artist} onChangeText={setArtist} /><Field label="الألبوم" value={album} onChangeText={setAlbum} /><Text style={styles.label}>الكلمات</Text><TextInput value={lyrics} onChangeText={setLyrics} placeholder="ألصق كلمات الأغنية هنا لعرضها أثناء التشغيل" placeholderTextColor={colors.muted} multiline textAlign="right" style={styles.lyricsInput} /><Pressable onPress={() => void save()} style={({ pressed }) => [styles.saveButton, pressed && styles.dimmed]}><Text style={styles.saveButtonText}>حفظ كل التعديلات</Text></Pressable></ScrollView></ScreenContainer>;
}
function Field({ label, value, onChangeText }: { label: string; value: string; onChangeText: (value: string) => void }) { return <View style={styles.fieldWrap}><Text style={styles.label}>{label}</Text><TextInput value={value} onChangeText={onChangeText} placeholder={label} placeholderTextColor={colors.muted} textAlign="right" style={styles.input} /></View>; }
function saveCoverLocally(sourceUri: string) { try { const directory = new Directory(Paths.document, "remo-player-covers"); if (!directory.exists) directory.create({ idempotent: true, intermediates: true }); const destination = new File(directory, `cover-${Date.now()}.jpg`); new File(sourceUri).copy(destination); return destination.uri; } catch { return sourceUri; } }
const styles = StyleSheet.create({ content: { paddingBottom: 32 }, header: { height: 60, paddingHorizontal: 16, flexDirection: "row-reverse", alignItems: "center", justifyContent: "space-between" }, headerButton: { width: 40, height: 40, borderRadius: 20, alignItems: "center", justifyContent: "center" }, headerTitle: { color: colors.text, fontSize: 16, fontWeight: "900" }, saveHeader: { minWidth: 40, alignItems: "center" }, saveHeaderText: { color: colors.cyan, fontSize: 14, fontWeight: "900" }, coverPicker: { width: 142, height: 142, borderRadius: 25, overflow: "hidden", alignSelf: "center", backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, marginTop: 12 }, coverImage: { width: "100%", height: "100%" }, coverFallback: { flex: 1, alignItems: "center", justifyContent: "center" }, coverEdit: { position: "absolute", width: 36, height: 36, borderRadius: 18, backgroundColor: colors.cyan, alignItems: "center", justifyContent: "center", left: 9, bottom: 9 }, coverHint: { color: colors.muted, fontSize: 11, textAlign: "center", marginTop: 9 }, fieldWrap: { marginHorizontal: 18, marginTop: 17 }, label: { color: colors.text, fontSize: 12, fontWeight: "800", textAlign: "right", marginBottom: 7 }, input: { minHeight: 48, borderRadius: 14, paddingHorizontal: 13, color: colors.text, fontSize: 14, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }, lyricsInput: { minHeight: 142, marginHorizontal: 18, borderRadius: 14, padding: 13, color: colors.text, fontSize: 14, lineHeight: 21, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, textAlignVertical: "top" }, saveButton: { minHeight: 50, marginHorizontal: 18, marginTop: 23, borderRadius: 15, alignItems: "center", justifyContent: "center", backgroundColor: colors.cyan }, saveButtonText: { color: colors.background, fontSize: 14, fontWeight: "900" }, dimmed: { opacity: 0.62 }, empty: { flex: 1, alignItems: "center", justifyContent: "center" }, emptyText: { color: colors.muted } });
