plugins {
    id 'com.android.application'
}

android {
    namespace 'com.remokeyboard.ime'
    compileSdk 35

    defaultConfig {
        applicationId 'com.remokeyboard.ime'
        minSdk 21
        targetSdk 35
        versionCode 5
        versionName '1.0.5'
    }

    buildFeatures { buildConfig true }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
